### ISSUE TITLE
Sustainsys.Saml2.Tests.pfx file Missing

### ISSUE THREAD

**Issue by rayray1039** [marlinspike/SustainSys-SAML-Federation-MVC#1]
The initial web-page loads, but all links with destinations other than '...sample application' and 'home' result in an error page:

"Server Error in '/' Application.
The system cannot find the file specified...."

Visual studio shows a warning 'does not exist in the project directory'  for the file in the Solution Explorer.

The web.config references Sustainsys.Saml2.Tests.pfx in the ~/App_Data folder.  The only file in that directory is a .cer file.

**Comment by marlinspike** [comment]
Hi RayRay1039 -- You have to log in using the link for the SustainSys IDP first, before you can use the "Secure" link. You've got two options to log in -- either your own IdP (first sign in link), or use the second Sign-In link, which uses the SustainSys sample IdP ("Sign in - https://stubidp.sustainsys.com/Metadata - https://stubidp.sustainsys.com/").

This second option is what you'd probably use getting started. This takes you to the SustainSys IdP, where you can use the default parameters, and inject any others you'd like. When you click **Log In** on the SustainSys site, it takes you back to the local web app, and now you're logged in. You can then click the **Secure** link at the top of the page, to simulate a link that's protected.

**Comment by rayray1039** [comment]
Thank you for the reply, Reuben.
I can not get to 'any' log in prompts, as I am not able to get past the missing file errors.  
There seems to be a Sustainsys.Saml2.Tests.pfx file missing from the visual studio project App_Data folder that is referenced in the web.config file's <serviceCertificates> section. This folder has a yellow warning glyph next to it, and when i double click on it, Visual studio reports that the file does not exist.  
When I run the project in chrome, a page does open but none of the log links work.
Links where I get a 'file not found ' error :

   
   - Sign in - default IDP
   - Sign in - https://stubidp.sustainsys.com/Metadata = https://stubidp.sustainsys.com/
   - Service Provider Metadata
   - Secure

The links that work: (they only seem to  refresh the page, but I include them for completeness)
   
   - Sustainsys.Saml2.Mvc Sample Application
   - Home

If there is any other information I can provide, please let me know.
Thanks,
-Ray







-----Original Message-----
